## Préambule
site_name: site_mkdocs
repo_name: Bitbucket
repo_url:
site_url: 
site_description: "Un site sur quelque chose."
site_author: Steven
copyright: <a rel="license"

#google_analytics:

theme: 
  name: readthedocs # mkdocs material


## Architecture
nav:
  - Accueil: index.md
  - Guide:
    - Pense-bete: pense_bete.md

## Extensions
markdown_extensions:
  - def_list
  - fenced_code
  - footnotes
  - tables
  - admonition
  - nl2br
  - sane_lists
  - smarty
  - toc:
      permalink: true
      baselevel: 1 # changement

